DEBUG 2024-04-11 15:15:35.568 UTC: 	 CRAB Client version: v3.240110
DEBUG 2024-04-11 15:15:35.568 UTC: 	 Running on: Linux lxplus910.cern.ch 5.14.0-362.24.1.el9_3.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Feb 15 07:18:13 EST 2024 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux 9.3 (Plow)
DEBUG 2024-04-11 15:15:35.568 UTC: 	 Executing command: 'status'
DEBUG 2024-04-11 15:15:35.570 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/joshin/.crab3
ERROR 2024-04-11 15:15:35.582 UTC: 	 Error: /afs/cern.ch/user/j/joshin/public/Efficiency/CMSSW_13_3_0_pre2/src/Workspace-RPC/240411/crab/crab_muRPCTnPFlatTableProducer_cfg__Muon1__Run2023D-PromptReco-v2__240411-133730 is not a valid CRAB project directory.
ERROR 2024-04-11 15:15:35.582 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/SubCommand.py", line 674, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: /afs/cern.ch/user/j/joshin/public/Efficiency/CMSSW_13_3_0_pre2/src/Workspace-RPC/240411/crab/crab_muRPCTnPFlatTableProducer_cfg__Muon1__Run2023D-PromptReco-v2__240411-133730 is not a valid CRAB project directory.
INFO 2024-04-11 15:15:35.692 UTC: 	 Log file is /afs/cern.ch/user/j/joshin/public/Efficiency/CMSSW_13_3_0_pre2/src/Workspace-RPC/240411/crab_1330pre2/crab.log
